### PR TITLE
Do not trust all certificates

### PR DESCRIPTION
**Pull request by DerEingerostete**
Instead of trusting all certificates for every HTTPS request use a custom SSLContext for the ObjectMapper. By having a custom SSL Certificate containing only the certificate for a Hue Bridge all requests are invalid besides the Hue Bridge. Therefore the custom SSLContext is only set for the ObjectMapper object and not as default for every HTTPS request.

Note: Older Hue Bridges currently still use self-signed certificates (instead of signed by Signify’s Hue Bridge CA). Therefore HTTPS requests from HueBridgeConnectionBuilder and HueBridgeDiscoveryService don't validate the certificate

### CODE REVIEW

**Comment by ZeroOne3010** [comment]
@DerEingerostete Hey, thank you very much for your pull request, and sorry for the slow response time! 🙏  There are some conflicts with the current code, but I'm in the process of merging your changes to master manually. 

By the way, what do you make of the `HueBridgeProtocol` enum now? The value is "UNVERIFIED_HTTPS", but now that you added the certificate, it's verified, isn't it? I could still change the enum value to just "HTTPS" for library version 3, as it's only in beta now.

**Comment by DerEingerostete** [comment]
> @DerEingerostete Hey, thank you very much for your pull request, and sorry for the slow response time! 🙏 There are some conflicts with the current code, but I'm in the process of merging your changes to master manually.
> 
> By the way, what do you make of the `HueBridgeProtocol` enum now? The value is "UNVERIFIED_HTTPS", but now that you added the certificate, it's verified, isn't it? I could still change the enum value to just "HTTPS" for library version 3, as it's only in beta now.

Yeah my bad. I just did that without remembering that it should now be called "HTTPS".

**Comment by DerEingerostete** [comment]
I've revised my pull request and updated some stuff:
- Renamed UNVERIFIED_HTTPS to HTTPS
- Renamed UNVERIFIED_TRUST_EVERYTHING_HTTPS back to UNVERIFIED_HTTPS 
- UNVERIFIED_HTTPS now doesn't override the global settings for trusting certificates and instead also uses the SecureJsonFactory class
- Updated HueBridgeDiscoveryService#discoverBridges(Consumer<HueBridge>, DiscoveryMethod...) to use by default HTTPS
- Added the method HueBridgeDiscoveryService#discoverBridges(Consumer<HueBridge>, HueBridgeProtocol, DiscoveryMethod...) to allow developers to define the protocol used for retrieving the configuration of discovered bridges

**Comment by ZeroOne3010** [comment]
Cool, looking better now! I wonder if you could still pull the latest changes from the upstream? As it stands, this PR cannot be merged due to some conflicts... HueBridgeConnectionBuilder, for one, has become a new class file of its own, it's not an inner class anymore. I know it's my fault for not reacting to this PR earlier, though, and just keeping on developing... 😞 And there's now new code to access the new version of the API as well, which should (eventually) be changed according to your PR as well.

**Comment by DerEingerostete** [comment]
I should have fixed all conflicts. But please be so kind and still take a look at my changes fixing the merge conflicts.
It seems like you removed the Hue.java constructor and the HueBridgeConnectionBuilder class. Was this on purpose?

**Comment by ZeroOne3010** [comment]
The connection builder I took out of the Hue class and into its own file. Removing the constructor was possibly because the connection type enum became unneeded, although with your changes it is useful again.

There is now another Hue class in the .v2 package, that should eventually replace the old Hue class entirely.

**Pull request merged**
